apiVersion: v1
kind: Service
metadata:
  name: aci-backend
  namespace: ${NAMESPACE}
  labels:
    app: aci-backend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: aci-backend
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800