FROM python:3.12
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /workdir

COPY ./pyproject.toml ./uv.lock /workdir/

RUN uv sync --no-install-project

ENV PATH="/workdir/.venv/bin:$PATH"
ENV PYTHONPATH=/workdir

RUN apt-get clean && rm -rf /var/lib/apt/lists/* && \
    mkdir -p /var/cache/apt/archives/partial && \
    playwright install chromium --with-deps --no-shell || true
