apiVersion: v1
kind: Service
metadata:
  name: aci-frontend
  namespace: ${NAMESPACE}
  labels:
    app: aci-frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: aci-frontend